# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Bevy' do

end

pod 'Google/Analytics'

pod 'CardIO'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4'
pod 'Flurry-iOS-SDK/FlurrySDK', '7.1.0'